[package]
name = "client"
version = "0.1.0"
edition = "2021"

[dependencies]
protocol = { path = "../protocol" }
logic = { path = "../logic" }
thiserror = "2.0.3"
tokio = { version = "1.41.1", features = ["full"] }
arrayvec = "0.7.6"
